pipeline {
    agent any

    tools {
        jdk 'jdk21' // This name must match the JDK installation name used in Jenkins Global Tool Configuration
    }
    environment {
        DOCKER_USERNAME = credentials('docker_username')
        DOCKER_PASSWORD = credentials('docker_password')
        IMAGE_VERSION = '1.1.0'
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_USERNAME/hello-img:$IMAGE_VERSION -f Dockerfile .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                sh 'docker push $DOCKER_USERNAME/hello-img:$IMAGE_VERSION'
            }
        }
    }
}
